config_file: config/train_params.yaml
model_type: gb
enable_validation: true
enable_monitoring: true
train:
  test_size: 0.2
  random_state: 42
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
data:
  target_column: quality
  feature_columns:
  - fixed acidity
  - volatile acidity
  - citric acid
  - residual sugar
  - chlorides
  - free sulfur dioxide
  - total sulfur dioxide
  - density
  - pH
  - sulphates
  - alcohol
